# -*- coding: utf-8 -*-
"""ChatGPT API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iqdPX2wnsbAfBCHeoS-_5SuFMUQV9cjv
"""

!pip install --upgrade openai

import requests
import json



URL = "https://api.openai.com/v1/chat/completions"
api_key = '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'

payload = {
"model" : "gpt-4-turbo-preview",
"messages":[
    {"role": "system", "content": "You are a programming assistant, skilled in writing complex programming concepts with creative syntax."},
    {"role": "user", "content": " Write a Python function in markdown that takes a sequence of numbers and determines whether all the numbers are different from each other. Return the code of the function only without any other text."}],
"temperature" : 1.0,
"top_p":1.0,
"n" : 5,
"stream": False,
"presence_penalty":0,
"frequency_penalty":0,
}

headers = {
"Content-Type": "application/json",
"Authorization": f"Bearer {api_key}"
}

response = requests.post(URL, headers=headers, json=payload, stream=False)

text = response.content.strip()

response_str_utf8 = text.decode("utf-8")

response_dict = json.loads(response_str_utf8)

total = 0
codes=[]
for choice in response_dict['choices']:
  sentence = choice['message']['content'].split()
  total += len(sentence)
  code = choice['message']['content'].replace('`',"")
  code = code.replace("python","")
  codes.append(code)

for code in codes:
  print(code)
  print("---------------------------------------------------")

print(response_dict)

