name: py27
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.9.0
  - astor=0.8.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports.weakref=1.0.post1
  - backports_abc=0.5
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - certifi=2020.6.20
  - configparser=3.7.3
  - contextlib2=0.6.0.post1
  - cycler=0.10.0
  - dbus=1.13.6
  - enum34=1.1.10
  - expat=2.6.3
  - fontconfig=2.14.2
  - freetype=2.12.1
  - funcsigs=1.0.2
  - functools32=3.2.3.2
  - futures=3.3.0
  - gast=0.4.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.66.3
  - grpcio=1.23.0
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=64.2
  - importlib-metadata=1.5.0
  - jpeg=9e
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.40
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=9.0.1
  - libexpat=2.6.3
  - libffi=3.2.1
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=3.0.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.66.3
  - libgomp=14.1.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm9=9.0.1
  - libopenblas=0.3.12
  - libpng=1.6.43
  - libprotobuf=3.11.4
  - libsqlite=3.46.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libuuid=2.38.1
  - libxcb=1.16
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - libzlib=1.2.13
  - markdown=3.3.3
  - matplotlib=2.2.5
  - matplotlib-base=2.2.5
  - mock=3.0.5
  - more-itertools=5.0.0
  - ncurses=6.5
  - nspr=4.35
  - nss=3.100
  - numpy=1.16.5
  - openssl=1.1.1w
  - pandas=0.24.2
  - pathlib2=2.3.5
  - patsy=0.5.1
  - pcre=8.45
  - protobuf=3.11.4
  - pthread-stubs=0.4
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - python=2.7.15
  - python-dateutil=2.8.1
  - python_abi=2.7
  - pytz=2020.1
  - qt=5.12.5
  - readline=8.2
  - scandir=1.10.0
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - seaborn=0.9.0
  - setuptools=44.0.0
  - singledispatch=3.6.1
  - six=1.16.0
  - sqlite=3.46.0
  - statsmodels=0.10.2
  - subprocess32=3.5.4
  - tensorboard=1.10.0
  - tensorflow=1.10.0
  - termcolor=1.1.0
  - tk=8.6.13
  - tornado=5.1.1
  - werkzeug=1.0.1
  - wheel=0.37.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zipp=1.0.0
  - zlib=1.2.13
  - pip:
      - backports-shutil-get-terminal-size==1.0.0
      - decorator==4.4.2
      - ipykernel==4.10.1
      - ipython==5.10.0
      - ipython-genutils==0.2.0
      - jupyter-client==5.3.5
      - jupyter-core==4.6.3
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pip==20.3.4
      - prompt-toolkit==1.0.18
      - ptyprocess==0.7.0
      - pygments==2.5.2
      - pyqt5-sip==4.19.18
      - pyqtwebengine==5.12.1
      - pyzmq==19.0.2
      - simplegeneric==0.8.1
      - traitlets==4.3.3
      - wcwidth==0.2.13
