services:
  dev-env:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_NAME=${USER_NAME}
        - USER_ID=${USER_ID}
        - GROUP_NAME=${GROUP_NAME}
        - GROUP_ID=${GROUP_ID}
    volumes:
      - .:/LLM-Code-Verifier
    command: tail -f /dev/null